### ISSUE TITLE
Kontrolle Aufgabe 03

### ISSUE THREAD

**Issue by MelvinBusch** [Lizzyfrmdblck/EIA2a#1]
1. Link zum Repository ganz oben im Steckbrief platzieren.
2. Aufgaben Ordner mit Unterordnern wie z.B. `ts` oder `konzept` zur besseren Übersicht strukturieren.
3. Bedingungen im AD immer in eckige Klammern schreiben.
4. `recieve click / keyboard Event` ist keine Bedingung sondern eine Aktion. Daher muss das in einen runden Kasten.
5. Es gibt keine Pfeile die ins Leere führen. Da muss noch was hinten dran kommen...
6. Zwei Event-Listener die auf das selbe Event warten bitte vermeiden. Das geht auch mit einem Listener.
7. Alle Event-Listener zur besseren Übersicht möglichst weit oben im Code platzieren.
8. Die Darstellung der gelegten Karten ist nicht besonders gut.
9. Zieht der Nutzer mehr Karten als es gibt, sind manche Karten doppelt.
10. Ansonsten alles in Ordnung 👍🏻

_15.04 | 12:36 (mb)_

**Comment by Plagiatus** [comment]
Die Karten sind allgemein schon doppelt, nicht nur am Ende..  
Tastendruck wird nicht überprüft ob es die Leertaste ist.

Wenn du schon alten Code kopierst, dann ändere doch wenigstens das Datum.

**Comment by Lizzyfrmdblck** [comment]
Hey Melvin, danke für dein Feedback!

Hey Lukas, vielleicht kannst du mir am Donnerstag ja erklären, was dagegen spricht den alten Code als Grundlage zu nutzen und umzuändern. 

Solange ich ihn verstehe, seh ich keinen Grund das anzuprangern, aber eventuell liege ich da ja auch falsch? ¯\_(ツ)_/¯

Beste Grüße

**Comment by Lizzyfrmdblck** [comment]
Hey Melvin, danke für dein Feedback!

Hey Lukas, vielleicht kannst du mir am Donnerstag ja erklären, was dagegen spricht den alten Code als Grundlage zu nutzen und umzuändern.

Solange ich ihn verstehe, seh ich keinen Grund das anzuprangern, aber eventuell liege ich da ja auch falsch? ¯\_(ツ)_/¯

Beste Grüße

**Comment by MelvinBusch** [comment]
Verteidigt. Code funktioniert. AD's noch nachreichen
